"""
Django settings for victoropsapp project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1o#b5pbcp_tm3_h)_x!2sor(2&%@*5bljoe!vl@1i!gvyih_^@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

BASE_URL = 'http://eec11cb2.ngrok.io'

YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YELLOWANT_CLIENT_ID = "DXMu0IhAngKpcqoieGxjzPQEr5FZLKnMODMDj7Rx"
YELLOWANT_CLIENT_SECRET = "Z1pTXQvSUOrWjMB0qhkpe6Z6CMKSkqKcORQaf6kp01wEtRROAA9qASwkeYBOA83fEOGrmtAOLFEa5AOKvEJL645Ud0q1w3iCSwEd7e5tlj2OIfgguwCEsReSjm3IK12O"
YELLOWANT_VERIFICATION_TOKEN = "9fINDatAr6YL5wX9OvybcLnxQRYoFhRUl2nl6vKE3mcJO302vSvv16olV2vyywwerqTGea1blStxv9XR8nczzMqrEOXKveTGuWrnaMtyIKVUTfkJjwYCXVdutEkVJa92"
YELLOWANT_REDIRECT_URL = BASE_URL + "/redirecturl/"

VICTOROPS_API_ID = '90bf5258'
VICTOROPS_API_KEY = 'f5fd61c10d269273c06cff705a630a9b'
VICTOROPS_INCIDENT_ALERT_URL = 'https://api.victorops.com/api-public/v1/alerts/'
VICTOROPS_ALL_USERS = 'https://api.victorops.com/api-public/v1/user'
VICTOROPS_CREATE_INCIDENT = "https://api.victorops.com/api-public/v1/incidents"
VICTOROPS_ADD_USER = "https://api.victorops.com/api-public/v1/user"
VICTOROPS_ACK_INCIDENTS = "https://api.victorops.com/api-public/v1/incidents/ack"
VICTOROPS_RESOLVE_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/resolve'
VICTOROPS_ACK_ALL_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/byUser/ack'
VICTOROPS_RESOLVE_ALL_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/byUser/resolve'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'records'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'victoropsapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'victoropsapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'victorops',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
