"""
Django settings for victoropsapp project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import json

data = open('yellowant_app_credentials.json').read()
data_json = json.loads(data)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1o#b5pbcp_tm3_h)_x!2sor(2&%@*5bljoe!vl@1i!gvyih_^@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

app_name = os.environ.get("HEROKU_APP_NAME")
BASE_URL = "https://{}.herokuapp.com".format(app_name)
ALLOWED_HOSTS = ['*', '{}.herokuapp.com'.format(app_name)]

BASE_HREF = "/"
SITE_PROTOCOL = "http://"


DEV_ENV = os.environ.get('ENV', 'DEV')
if DEV_ENV == "DEV":
    BASE_URL = "https://dd272eb3.ngrok.io"
    SITE_DOMAIN_URL = "ngrok.io"
elif DEV_ENV == "HEROKU":
    BASE_URL = "https://{}.herokuapp.com/".format(app_name)
    app_name = os.environ.get("HEROKU_APP_NAME")
    SITE_DOMAIN_URL = "herokuapp.com"


YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YELLOWANT_APP_ID = str(data_json['application_id'])
YELLOWANT_CLIENT_ID = str(data_json['client_id'])
YELLOWANT_CLIENT_SECRET = str(data_json['client_secret'])
YELLOWANT_VERIFICATION_TOKEN = str(data_json['verification_token'])
YELLOWANT_REDIRECT_URL = BASE_URL + "redirecturl/"


VICTOROPS_INCIDENT_ALERT_URL = 'https://api.victorops.com/api-public/v1/alerts/'
VICTOROPS_ALL_USERS = 'https://api.victorops.com/api-public/v1/user'
VICTOROPS_CREATE_INCIDENT = "https://api.victorops.com/api-public/v1/incidents"
VICTOROPS_ADD_USER = "https://api.victorops.com/api-public/v1/user"
VICTOROPS_ACK_INCIDENTS = "https://api.victorops.com/api-public/v1/incidents/ack"
VICTOROPS_RESOLVE_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/resolve'
VICTOROPS_ACK_ALL_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/byUser/ack'
VICTOROPS_RESOLVE_ALL_INCIDENTS = 'https://api.victorops.com/api-public/v1/incidents/byUser/resolve'
# Application definition

INSTALLED_APPS = [
    'lib.web',
    'lib.records',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'victoropsapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'victoropsapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'victorops',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '',
    }
}
if DEV_ENV == "HEROKU":
    import dj_database_url
    db_from_env = dj_database_url.config()
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['CONN_MAX_AGE'] = 500


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
