# Generated by Django 2.0.2 on 2018-05-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victoropsusertoken',
            old_name='victorops_api_id',
            new_name='victorops_user_id',
        ),
        migrations.RemoveField(
            model_name='victoropsusertoken',
            name='victorops_api_key',
        ),
    ]
