# Generated by Django 2.0.2 on 2018-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180517_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='victoropsusertoken',
            name='victorops_api_id',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victoropsusertoken',
            name='victorops_api_key',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
