# Generated by Django 2.0.2 on 2018-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_victoropsusertoken_apikey_login_update_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowusertoken',
            name='user',
            field=models.IntegerField(),
        ),
    ]
